version: '3.8'

services:
  web:
    build: .
    ports:
      - "8001:8001"
    environment:
      - DEBUG=${DEBUG:-False}
      - SECRET_KEY=${SECRET_KEY:-your-production-secret-key-change-this}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1,0.0.0.0}
      - EMAIL_BACKEND=${EMAIL_BACKEND:-django.core.mail.backends.console.EmailBackend}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL:-noreply@portfolio.com}
      - EMAILJS_PUBLIC_KEY=${EMAILJS_PUBLIC_KEY:-}
      - EMAILJS_SERVICE_ID=${EMAILJS_SERVICE_ID:-}
      - EMAILJS_TEMPLATE_ID=${EMAILJS_TEMPLATE_ID:-}
      - EMAILJS_TO_EMAIL=${EMAILJS_TO_EMAIL:-}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@portfolio.com}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME:-admin}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL:-admin@portfolio.com}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD:-admin123}
    volumes:
      # Mount media files for persistence
      - media_data:/app/media
      # Mount database directory for persistence
      - db_data:/app/data
      # Mount logs for debugging
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service with hot reload
  web-dev:
    build:
      context: .
      target: production
    ports:
      - "8001:8001"
    environment:
      - DEBUG=True
      - SECRET_KEY=${DEV_SECRET_KEY:-dev-secret-key-not-for-production}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1,0.0.0.0}
      - EMAIL_BACKEND=${EMAIL_BACKEND:-django.core.mail.backends.console.EmailBackend}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL:-noreply@portfolio.com}
      - EMAILJS_PUBLIC_KEY=${EMAILJS_PUBLIC_KEY:-}
      - EMAILJS_SERVICE_ID=${EMAILJS_SERVICE_ID:-}
      - EMAILJS_TEMPLATE_ID=${EMAILJS_TEMPLATE_ID:-}
      - EMAILJS_TO_EMAIL=${EMAILJS_TO_EMAIL:-}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@portfolio.com}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME:-admin}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL:-admin@portfolio.com}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD:-admin123}
    volumes:
      # Mount source code for development
      - .:/app
      - /app/node_modules
    command: python manage.py runserver 0.0.0.0:8001
    restart: unless-stopped
    profiles:
      - dev

volumes:
  media_data:
  db_data: